name = "PlutoPDF"
uuid = "6eb38059-8c05-41f7-8871-5e7e2697ace6"
license = "MIT"
authors = ["Fons van der Plas", "Connor Burns"]
version = "1.2.3"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NodeJS_20_jll = "c7aee132-11e1-519c-8219-0a43005e73c2"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
DefaultApplication = "1"
JSON = "0.20, 0.21, 1"
NodeJS_20_jll = "20"
Pluto = "0.20"
RelocatableFolders = "1"
Scratch = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
